-- Landmine Soft Gym Management Website - Database Schema
--
-- This schema is automatically generated by Hibernate (JPA) using the `ddl-auto: update`
-- property. The following SQL statements represent the tables created by the application.

CREATE TABLE `user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `role` enum('USER','ADMIN') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_sb8bbouer5wak8vyiiy4pf2bx` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `membership_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `duration` enum('MONTHLY','QUARTERLY','YEARLY') NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `features` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `trainer` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `specialization` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workout_schedule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `level` enum('BEGINNER','INTERMEDIATE','ADVANCED') NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subscription` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `plan_id` bigint NOT NULL,
  `trainer_id` bigint DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `status` enum('ACTIVE','EXPIRED') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKgq8c5vj7k5par3g7f383jdf5p` (`user_id`),
  KEY `FKb2p8v2g5g5y5j5h5j5h5j5h5j` (`plan_id`),
  KEY `FKc3v3j5k5k5l5m5n5n5n5n5n5` (`trainer_id`),
  CONSTRAINT `FKgq8c5vj7k5par3g7f383jdf5p` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FKb2p8v2g5g5y5j5h5j5h5j5h5j` FOREIGN KEY (`plan_id`) REFERENCES `membership_plan` (`id`),
  CONSTRAINT `FKc3v3j5k5k5l5m5n5n5n5n5n5` FOREIGN KEY (`trainer_id`) REFERENCES `trainer` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
